# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudgrep < Formula
  desc "Cloudgrep is an asset explorer for cloud resources"
  homepage "https://github.com/run-x/cloudgrep"
  version "0.0.39"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.39/cloudgrep_0.0.39_darwin_amd64.tar.gz"
      sha256 "fd5c92c297a8ce41a13cf4ca27d05071c225dc7f604871f37f57f324e40f4460"

      def install
        bin.install "cloudgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.39/cloudgrep_0.0.39_darwin_arm64.tar.gz"
      sha256 "4ee2974937cea0f5742bac66fdc86fd5c0a67ed42b9365bdca046cad7cf4acac"

      def install
        bin.install "cloudgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.39/cloudgrep_0.0.39_linux_arm64.tar.gz"
      sha256 "fec56d4234e7c67c6d893a6210ec64cbf4179cbdea49d15940d37c13fdf3c027"

      def install
        bin.install "cloudgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.39/cloudgrep_0.0.39_linux_amd64.tar.gz"
      sha256 "a00f05b108a75a6c1400f55016c38b2bdb2740389fe1414def103abfc6a0d1cd"

      def install
        bin.install "cloudgrep"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/cloudgrep version"
  end
end
