# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudgrep < Formula
  desc "Cloudgrep is an asset explorer for cloud resources"
  homepage "https://github.com/run-x/cloudgrep"
  version "0.0.29-beta2"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.29-beta2/cloudgrep_0.0.29-beta2_darwin_arm64.tar.gz"
      sha256 "89ca635f2552de60f042a4765799161e8f88dcddb31bece005f9dbed0ef249e2"

      def install
        bin.install "cloudgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.29-beta2/cloudgrep_0.0.29-beta2_darwin_amd64.tar.gz"
      sha256 "ad29568019062a4dcde1d15753a42d2b6ad628e2cacae7da5ba2a588f148cd95"

      def install
        bin.install "cloudgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.29-beta2/cloudgrep_0.0.29-beta2_linux_arm64.tar.gz"
      sha256 "67ac70df3c9a30ddbe9b905ec82525da4b1554d58cd5d614ccd5f0bcd6b35625"

      def install
        bin.install "cloudgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/run-x/cloudgrep/releases/download/v0.0.29-beta2/cloudgrep_0.0.29-beta2_linux_amd64.tar.gz"
      sha256 "eb8fbd1d3a738f8216e07da805c3a3e42186534d16765362cd874d9dc6ea2981"

      def install
        bin.install "cloudgrep"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/cloudgrep version"
  end
end
